businesscollector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path ('', include ('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

main_app/urls.py
from django.urls import path
from . import views

from django.urls import path
from . import views

urlpatterns =  [
    path ('', views.home, name = 'home'),
    path('businesses/', views.businesses_index, name='index'),
    path('businesses/<int:business_id>/', views.businesses_detail, name='detail'),
    path('myprofile/', views.my_profile, name='myprofile'),
    path('accounts/signup/', views.signup, name='signup'),
    path('businesses/create/', views.BusinessCreate.as_view(), name='businesses_create'),
    path('businesses/<int:pk>/update', views.BusinessesUpdate.as_view(), name='businesses_update'),
    path('businesses/<int:pk>/delete', views.BusinessesDelete.as_view(), name='businesses_delete'),
    path('business/<int:business_id>/add_product/', views.add_product, name='add_product'),
    path('business/<int:pk>/edit_product/', views.edit_product.as_view(), name='edit_product'),
    path('business/<int:pk>/delete_product/', views.delete_product.as_view(), name='delete_product'),
    path('businesses/<int:business_id>/favourites/<user_id>', views.favourites_add, name = 'favourites_add'), 
    path('businesses/<int:business_id>/favourites_delete/<user_id>', views.favourites_delete, name = 'favourites_delete'), 
    path('businesses/favourites', views.favourite_list, name = 'favourite_list')
]

main_app/models.py
from django.db import models
from datetime import date
from django.contrib.auth.models import User
from django.urls import reverse


CATEGORY = (
    ('Other', 'Other'),
    ('Home', 'Home'),
    ('Books', 'Books'),
    ('Food', 'Food'),
    ('Music', 'Music'),
    ('Jewelry', 'Jewelry'),
    ('Pets', 'Pets'),
    ('Stationery', 'Stationery'),
    ('Clothes', 'Clothes')
)

class Business(models.Model):
    name = models.CharField(max_length = 100)
    address = models.CharField(max_length = 100)
    city = models.CharField(max_length = 100)
    province = models.CharField(max_length = 100)
    postal_code = models.CharField(max_length = 100)
    website = models.URLField(max_length = 200)
    description = models.CharField(max_length=1000)
    category = models.CharField(
        max_length=10,
        choices=CATEGORY,
        default=CATEGORY[0][0]
    )
    image = models.ImageField(upload_to='businesscollector/',default='default.png',null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    favourites = models.ManyToManyField(
        User, related_name = 'favourite', default=None, blank=True)
    def __str__(self):
        return self.name
    def get_absolute_url(self):
        return reverse('detail', kwargs={'business_id': self.id})


class Product(models.Model):
    name = models.CharField(max_length = 100)
    description = models.CharField(max_length=1000)
    url = models.URLField(max_length = 200)
    image = models.ImageField(upload_to='businesscollector/',default='default.png',null=True)
    
    
    business = models.ForeignKey(Business, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.name

  

    

main_app/forms.py
from django.forms import ModelForm
from .models import Product 

class ProductForm(ModelForm):
    class Meta:
        model = Product 
        fields = ['name', 'description', 'url', 'image']

main_app/views.py
from dataclasses import fields
from itertools import product
from pyexpat import model
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import CreateView, UpdateView, DeleteView


from .models import Business, Product
from .forms import ProductForm
from .filter import BusinessFilter
import uuid
import boto3
S3_BASE_URL = 'http://s3.ca-central-1.amazonaws.com/'
BUCKET = 'businesscollector'









# Create your views here.
def home (request):
    return render (request, 'home.html')

def businesses_index(request):
    businesses = Business.objects.order_by('name')
    category_filter = BusinessFilter(request.GET, queryset=businesses, )

    return render(request, 'businesses/index.html', { 'businesses': businesses, 'category_filter': category_filter })

def businesses_detail(request, business_id):
  business = Business.objects.get(id=business_id)
  product = Product.objects.all()  
  product_form = ProductForm()
  if business.favourites.filter(id = request.user.id).exists():
    favourite = True
  else:
    favourite = False
  return render(request, 'businesses/detail.html', { 'business': business, 'favourite' : favourite, 'product_form': product_form, 'product': product})

def signup(request):
  error_message = ''
  if request.method == 'POST':
    # This is how to create a 'user' form object
    # that includes the data from the browser
    form = UserCreationForm(request.POST)
    if form.is_valid():
      # This will add the user to the database
      user = form.save()
      # This is how we log a user in via code
      login(request, user)
      return redirect('/')
    else:
      error_message = 'Invalid sign up - try again'
  # A bad POST or a GET request, so render signup.html with an empty form
  form = UserCreationForm()
  context = {'form': form, 'error_message': error_message}
  return render(request, 'registration/signup.html', context)


class BusinessCreate(LoginRequiredMixin, CreateView):
  model = Business
  fields =['name', 'address','city', 'province', 'postal_code', 'website', 'description', 'category', 'image']
  def form_valid(self, form):
    form.instance.user = self.request.user  
    return super().form_valid(form)

  

class BusinessesUpdate(LoginRequiredMixin, UpdateView):
  model = Business 
  fields = ['name', 'website', 'description', 'category']

class BusinessesDelete(LoginRequiredMixin, DeleteView):
  model = Business
  success_url = '/businesses/'  



@login_required
def my_profile(request):
  businesses = Business.objects.filter(user=request.user)
  return render(request, 'businesses/profile.html', { 'businesses': businesses})

@login_required
def add_product(request, business_id):
  form = ProductForm(request.POST, request.FILES)
  if form.is_valid():
    new_product = form.save(commit=False)
    new_product.business_id = business_id
    new_product.save()
  return redirect('detail', business_id=business_id)  

class edit_product(LoginRequiredMixin, UpdateView):
  model = Product
  fields =  ['description', 'url']
  success_url = '/businesses/{business_id}/'

class delete_product(LoginRequiredMixin, DeleteView):
  model = Product
  success_url = '/businesses/{business_id}/'
 
  
@login_required
def favourites_add (request, user_id, business_id):
  Business.objects.get(id=business_id).favourites.add(request.user)
  return redirect('detail', business_id=business_id)

@login_required
def favourites_delete (request, user_id, business_id):
  Business.objects.get(id=business_id).favourites.remove(request.user)
  return redirect('detail', business_id=business_id)



@login_required
def favourite_list (request):
  businesses = Business.objects.filter(favourites = request.user)
  return render(request, 'businesses/favourites.html', { 'businesses': businesses})

main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">


    <title>Document</title>
   
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    
<link href="https://fonts.googleapis.com/css2?family=Bentham&display=swap" rel="stylesheet">


</head>
<body>
    <nav>
        <h2 class = 'base-title'> <a href = '/'>shoplocalTO</a></h2>   
        <a href = '/businesses'>see all</a>
        {% if user.is_authenticated %}
            <a href = "{% url 'businesses_create' %}">submit a </br>business</a>
            <a href = "{% url 'favourite_list' %}">favourites</a>
            <a href = "{% url 'myprofile' %}"> see your </br>business</a>
            <a href = "{% url 'logout' %}">log out</a>
        {% else %}
        <a href="{% url 'signup' %}">sign up</a>
        <a href ="{% url 'login' %}">log in</a>
        {% endif %}
    </nav>


    {%block content%}
  
    {%endblock%}
</body>
</html>

main_app/templates/businesses/detail.html
{% extends 'base.html' %}
{% block content %}

<h1>{{ business.name }}</h1>


<div class="details-info-card ">
  <div class = 'details-image'style="background-image: url({{business.image.url}});"></div>
  <div class="details-text">
    <p>Category: </br>{{ business.category }}</p>
    <p>Description: </br>{{ business.description }}</p>
    <p>Address: </br>
    {{ business.address }}, {{ business.city }}</br>
    {{ business.province }} {{business.postal_code }}</p>
    <p><button><a href =  "{{ business.website }}">Shop Website </button></a></p>
    
        {%if favourite%}
        <form action="{% url 'favourites_delete' business.id user.id%}" method="post">
            {% csrf_token %}  
            <button type="submit" >
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="red" class="bi bi-heart-fill" viewBox="0 0 16 16">
                    <path fill-rule="evenodd" d="M8 1.314C12.438-3.248 23.534 4.735 8 15-7.534 4.736 3.562-3.248 8 1.314z"/>
                </svg> 
            Favourited
            </button>
        </form>

        {%else%}
        <form action="{% url 'favourites_add' business.id user.id%}" method="post">
            {% csrf_token %}  
            <button type="submit" >
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-heart" viewBox="0 0 16 16">
                    <path d="m8 2.748-.717-.737C5.6.281 2.514.878 1.4 3.053c-.523 1.023-.641 2.5.314 4.385.92 1.815 2.834 3.989 6.286 6.357 3.452-2.368 5.365-4.542 6.286-6.357.955-1.886.838-3.362.314-4.385C13.486.878 10.4.28 8.717 2.01L8 2.748zM8 15C-7.333 4.868 3.279-3.04 7.824 1.143c.06.055.119.112.176.171a3.12 3.12 0 0 1 .176-.17C12.72-3.042 23.333 4.867 8 15z"/>
                </svg> 
                Add to favourites
            </button>
        </form>

        {% endif %}






        {% if business.user == request.user %}

        <div class="card-action">
            <p><button> <a href="{% url 'businesses_update' business.id %}">Edit</a></button>
            <button><a href="{% url 'businesses_delete' business.id %}">Delete Business</a></button></p>
        </div>
        </div>
        {% else %}
        <div></div>
        {% endif %}
        </div>
</div>
</br>
</div>



<hr>
<div class ="all-product-cards">
  <div class = "product-info">
    <h2>{{ business.name }}'s Featured Products</h2>
    <br>
    
    {% for product in business.product_set.all %}
    <div class="product-card">
        <img src="{{product.image.url}}" > 
        <span class="card-title">{{ product.name }}</span>
        <br>
        <a href="{{ product.url }}">Product Website</a>
        <p>Description: {{ product.description }}</p>
        
        {% if business.user == request.user %}

        <a href="{% url 'edit_product' product.id %}"><button>Edit</button></a>
        <a href="{% url 'delete_product' product.id %}"><button>Delete</button></a>
        {%endif%}
        
    </div>
    {% endfor %}

    
  </div>

{% if business.user == request.user %}
  <hr>
  <div class = 'add-new-product-form'>
    <h3>add a product</h3>
    <div id="col3">
      <form action="{% url 'add_product' business.id %}" method="post"enctype="multipart/form-data">
        {% csrf_token %}
        <table>
          {{ product_form.as_table }}
        </table>
        </br>
        <button type="submit" >Add Product</button>
      </form>
    </div>
  </div>
</div>

{%endif%}




  {% endblock %}

main_app/templates/businesses/favourites.html
{% extends 'base.html' %}
{% block content %}

{% if businesses.count %}
    {% for business in businesses %}
    <a href="{% url 'detail' business.id %}">
        <div class="card" style="background-image: url({{business.image.url}});">
                <div class="card-content">
                <span class="card-title">{{ business.name }}</span>
                </br>
                <p>Category: {{ business.category }}</p>

                </div>
        </div>
    </a>

    {% endfor %}
{% else %}
    <h3>No favourites added yet. <a href = "{% url 'index' %}">Browse businessses</a></h3>

{% endif %}


{% endblock %}

main_app/templates/businesses/index.html
{% extends 'base.html' %}
{% block content %}

<h1>business listings</h1>
<div class = 'index_info'>
  <form method="GET">
    {{category_filter.form}} <button type = 'submit'>search</button>
  </form>
</div>
{% for category in category_filter.qs %}
<a href="{% url 'detail' category.id %}">
  <div class="card" style="background-image: url({{category.image.url}});">
          <div class="card-content">
          <span class="card-title">{{ category.name }}</span>
          </br>
          <p>Category: {{ category.category }}</p>

          </div>
  </div>
</a>

{% endfor %}

{% endblock %}

main_app/templates/businesses/profile.html
{% extends 'base.html' %}
{% block content %}

<h1>my business listings</h1>

<h1>{{user.name}}</h1>

{% if businesses.count %}
    {% for business in businesses %}
    <a href="{% url 'detail' business.id %}">

        <div class="card" style="background-image: url({{business.image.url}});">
            <!-- <img src= "{{business.image.url}}"> -->
                <div class="card-content">
                <span class="card-title">{{ business.name }}</span>
                </br>
                <p>Category: {{ business.category }}</p>

                </div>
        </div>
    </a>
    {% endfor %}
{% else %}
    <h3>No businesses added yet. <a href = "{% url 'businesses_create' %}">Add a business!</a></h3>
{% endif %}

{% endblock %}

main_app/templates/home.html
{% extends 'base.html' %}
{% block content %}
<div class = 'home-page'></div>
    <div class = 'home-page-text'>
        <h1>WELCOME!</h1>
        <h2> We're here to help you shop and support local!</h2>
    </div>

<div class = 'homecard'> 
    <a href = '/businesses'>BROWSE LOCAL </a>
    <a href = "{% url 'businesses_create' %}">SUBMIT A BUSINESS</a>

</div>

{%endblock%}

main_app/templates/main_app/business_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
<h1>Delete Business</h1>
<div class="delete-form">

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete My Business!" class="btn">
    <a href="{% url 'detail' business.id %}"><button class="btn">Cancel</button></a>
  </form>
</div>
{% endblock %}

main_app/templates/main_app/business_form.html
{% extends 'base.html' %}

{% block content %}
{% if object %}
    <h1>Edit <span class="teal-text">{{object.name}}</span></h1>
  {% else %}
    <h1>Submit a Business</h1>
  {% endif %}


  <div class="createform">
  <form action="" method="post" enctype="multipart/form-data">
    
    {% csrf_token %}
    <table>
      
      {{ form.as_table }}
    </table>
  </BR>
    <button type="submit" >Submit</button>

  </form>
</div>
{% endblock %}

main_app/templates/main_app/product_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Product</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'detail' product.id %}"><button class="btn">Cancel</button></a>
  </form>
{% endblock %}

main_app/templates/main_app/product_form.html
{% extends 'base.html' %}

{% block content %}
  <!-- New if/else block -->
  {% if object %}
  <h1>Edit <span class="teal-text">{{object.name}}</span></h1>
  <form action="" method="post">
    <!-- Django requires the following for security purposes -->
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
  </form>
  {% else %}
    <h1>Add Product</h1>
  {% endif %}

  {%endblock%}